module.exports = {
    isOffline: false,
    BACKDROP_PATH: '"https://image.tmdb.org/t/p/original"',
    IMAGE_PATH: '"https://image.tmdb.org/t/p/w300"',
    NODE_ENV: '"production"',
    OMDB_API_KEY: '"636bd88a"',
    OMDB_BASE_URL: '"http://www.omdbapi.com/"',
    OMDB_MOVIE_DETAILS: '""',
    OMDB_SHOW_DETAILS: '""',
    SEARCH: '"search/"',
    SEARCH_MOVIE: '"movie"',
    SEARCH_SERIES: '"tv"',
    SEARCH_PEOPLE: '"person"',
    SELECT_AIRING_TODAY: '"/airing_today"',
    SELECT_NOW_PLAYING: '"/now_playing"',
    SELECT_UPCOMING: '"/upcoming"',
    SELECT_ON_THE_AIR: '"/on_the_air"',
    SELECT_POPULAR: '"/popular"',
    SELECT_TOP_RATED: '"/top_rated"',
    TMDB_API_KEY: '"0312d542ff3bc63a78d6647fe5727160"',
    TMDB_BASE_URL: '"https://api.themoviedb.org/3/"',
    TMDB_MOVIE_DETAILS: '"movie/"',
    TMDB_SHOW_DETAILS: '"tv/"',
    TMDB_PERSON_DETAILS: '"person/"'
}
